
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: euphony_development


test: &test
  <<: *default
  database: euphony_test

production:
  <<: *default
  database: euphony_production

cucumber:
  <<: *test
